# Generated by Django 5.1.7 on 2026-06-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='cars', to='app.subcategory'),
        ),
    ]
