# Generated by Django 5.1.7 on 2026-06-01 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_car_subcategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price_saturday',
            new_name='price_weekend',
        ),
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_sunday',
        ),
    ]
